spring:
  application:
    name: blog
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.254:3306/db2022108012
    username: user2022108012
    password: 2022108012